---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-hello-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-hello-world
  strategy: 
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: gke-hello-world
    spec:
      containers:
      - name: hello-app
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
          limits:
            cpu: 200m

---
apiVersion: "v1"
kind: Service
metadata: 
  name: s-gke-hello-world
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: gke-hello-world
