# This is a basic workflow to help you get started with Actions

name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:
  
  
env:
  PROJECT_ID: ${{secrets.GKE_PROJECT}}
  GKE_CLUSTER: gke-dev-stftaller001
  GKE_ZONE: us-east1-b
  DEPLOYMENT_NAME: gke-hello-app
jobs:
  build:
    name: Setup and deploy
    runs-on: ubuntu-latest
    
    permissions: 
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
            credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
   
      -
        name: Set up cloud sdk
        uses: google-github-actions/setup-gcloud@v0
        
          
      - run: |-
          gcloud container clusters get-credentials "gke-dev-stftaller001" --zone "us-east1-b"
      - name: Deploy
        run: |-
          kubectl apply -f deployment.yml
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
